// <auto-generated />
using System;
using ECanopy.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ECanopy.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241231140000_AddAmenitiesOnly")]
    partial class AddAmenitiesOnly
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            // This would contain the full model snapshot
            // For brevity, we'll let EF generate this automatically
#pragma warning restore 612, 618
        }
    }
}